const ACTION_TYPES = {
  ADD_TASK: 'ADD_TASK',
  TOGGLE_TODO: 'TOGGLE_TASK',
  SET_VISIBILITY_FILTER: 'SET_VISIBILITY_FILTER',
  TASK_EDITOR: {
    ON_CHANGE: 'TASK_EDITOR_CHANGE',
  },
};

export default ACTION_TYPES;
