const ACTION_TYPES = {
  TOGGLE_WHITE_MODE: 'TOGGLE_WHITE_MODE',
  TOGGLE_SIDEBAR: 'TOGGLE_SIDEBAR',
  CHANGE_CWD: 'CHANGE_CWD',
  TOGGLE_SETTINGS: 'TOGGLE_SETTINGS',
  CHANGE_CPP: 'CHANGE_CPP',
  CARD_EDITOR: {
    ON_CHANGE: 'CARD_EDITOR_CHANGE',
    TOGGLE_EDITOR: 'TOGGLE_EDITOR',
    EDIT_CARD: 'EDIT_CARD',
  },
  CARD: {
    ADD_CARD: 'ADD_CARD',
    SAVE_CARD: 'SAVE_CARD',
    EDIT_CARD: 'EDIT_CARD',
    REMOVE_CARD: 'REMOVE_CARD',
    TOGGLE_CARD: 'TOGGLE_CARD',
    GENERATE_LINK: 'GENERATE_NOTE_LINK',
    CHANGE_TITLE: 'CHANGE_TITLE',
  },
  LABEL: {
    ADD_LABEL: 'ADD_LABEL',
    REMOVE_LABEL: 'REMOVE_LABEL',
  },
  FILTERS: {
    FOCUS_CARD: 'FOCUS_CARD',
    CHANGE_SORTING_STATE: 'CHANGE_SORTING_STATE',
    SEARCH_CARDS: 'SEARCH_CARDS',
    TOGGLE_COMPLETED_FILTER: 'TOGGLE_COMPLETED_FILTER',
    ADD_LABEL_FILTER: 'ADD_LABEL_FILTER',
    REMOVE_LABEL_FILTER: 'REMOVE_LABEL_FILTER',
  },
};

export default ACTION_TYPES;
